services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
